### ISSUE TITLE
AsyncTasks in MaterialAccount should not be instanciated at class initialization

### ISSUE THREAD

**Issue by mlumeau** [neokree/MaterialNavigationDrawer#143] opened 2015-01-28 16:18 UTC
When manipulating a MaterialAccount, it can happen that setPhoto() is called twice in a short timespan. In that case, an IllegalStateException is thrown, because you cannot execute the same instance of an AsyncTask while it is already executing.

A workaround would be to define AsyncTask inner classes of MaterialAccount (ResizePhotoBitmapAsyncTask, ResizeBackgroundBitmapAsyncTask...) and define setPhotoBitmap, setBackgroundBitmap, etc... as the following: 
```java
public void setPhoto(Bitmap photo) {
    new ResizePhotoBitmapAsyncTask().execute(photo);
} `

**Comment by neokree** [comment] 2015-01-30 23:37
I followed your suggestion and committed now a little fix, please check if now the problem is resolved.

**Comment by mlumeau** [comment] 2015-02-05 15:00
That did it. Everything runs perfectly with your fix.
Thanks.

**Closed** 2015-02-15 11:20 UTC
Labels: available in the next release
