### ISSUE TITLE
Remove a MaterialAccount, but notifyAccountDataChanged not work

### ISSUE THREAD

**Issue by TakumaMochizuki** [neokree/MaterialNavigationDrawer#172] opened 2015-02-12 09:12 UTC
Hello neokree,

I want to remove an account in List<MaterialAccount> accountManager, and It's work, after that I call notifyAccountDataChanged method to update header, but not work, Did I do anything wrong?

**Comment by neokree** [comment] 2015-02-12 18:44
how have you removed the account from the account list? could you post some code? Thank you

**Comment by TakumaMochizuki** [comment] 2015-02-12 19:31
Like this code: 

```
public void init(Bundle bundle) {
        aAccount = new MaterialAccount(getResources(), "Quest", "no comment",  icon, background);
        bAccount = new MaterialAccount(getResources(), "Quest", "no comment",  icon, background);
        addAccount(aAccount);
        addAccount(bAccount);
}

// Call this method in main thread or back thread
private void refreshAccount() {
        getAccountList().remove(aAccount);
        notifyAccountDataChanged();        // not work
}
```

Thank you :)

**Comment by neokree** [comment] 2015-02-14 03:31
The problem is this: MaterialAccount is a dataset class. It is not supposed to be used like a view class.
When you remove the account from the main list, you have only removed the account datas. 
I'm creating the <code>removeAccount</code> method for doing this.

**Comment by neokree** [comment] 2015-02-15 13:24
I committed now the dev version with the <code>removeAccount()</code> method.

**Comment by TakumaMochizuki** [comment] 2015-02-15 14:03
Thanks a lot. :)

**Comment by neokree** [comment] 2015-02-15 14:43
try to use the dev project avariable on github please, I have tested some possibility, but if you find some bugs please let me know.

**Closed** 2015-12-22 18:31 UTC
Labels: testing
