### ISSUE TITLE
Getting Fragment must be android.app.Fragment or android.support.v4.app.Fragment

### ISSUE THREAD

**Issue by alexmilano** [neokree/MaterialNavigationDrawer#82] opened 2015-01-05 20:03 UTC
Hi, I tried the lib, and I have the init method.. I removed the onCreate of my Activity.. But I am getting the error: Fragment must be android.app.Fragment or android.support.v4.app.Fragment

ATAL EXCEPTION: main
    Process: com.lifekee.app, PID: 8430
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.lifekee.app/com.lifekee.app.activities.contact.MainActivity}: java.lang.RuntimeException: Fragment must be android.app.Fragment or android.support.v4.app.Fragment
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
     Caused by: java.lang.RuntimeException: Fragment must be android.app.Fragment or android.support.v4.app.Fragment
            at it.neokree.materialnavigationdrawer.MaterialNavigationDrawer.setFragment(MaterialNavigationDrawer.java:618)
            at it.neokree.materialnavigationdrawer.MaterialNavigationDrawer.onCreate(MaterialNavigationDrawer.java:460)
            at android.app.Activity.performCreate(Activity.java:5933)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by randombyte-developer** [comment] 2015-01-05 21:03
I want to say, that you should use an intent or an fragment. Anyway. I found hopefully the solution in the wiki:

NOTE that the first section you added is opened when the activity starts, so it must have a Fragment as target.

So, you have to use a fragment in the first position.

**Comment by alexmilano** [comment] 2015-01-05 21:47
Well, now I get the error:
Caused by: java.lang.IllegalArgumentException: No view found for id 0x7f0c0069 (com.lifekee.app:id/frame_container) for fragment SampleListFragment{10174a8b #1 id=0x7f0c0069}

**Comment by neokree** [comment] 2015-01-05 22:40
maybe related with #81 ?

**Comment by h0aX14** [comment] 2015-01-06 06:08
@alexmilano , can you post that particular Fragment subclass along with import statements ?

**Comment by younes0** [comment] 2015-01-06 09:51
Maybe this error is caused by the presence of `setContentView(R.layout.activity_main)` in your activity

**Comment by neokree** [comment] 2015-01-24 14:02
@alexmilano if you have resolved your problem, please close this issue.

**Closed** 2015-01-24 14:03 UTC
