### ISSUE TITLE
Scrollview not working inside Fragment

### ISSUE THREAD

**Issue by h4ck3rviv3k** [neokree/MaterialNavigationDrawer#303] opened 2015-05-29 16:31 UTC
I have multiple Edittext in a fragment when I tap on any of the Edittext keyboard gets poped up and Edittext will get hide behind the keyboard. It won't scroll upto the Editext.

Please try to replicate this issue and resolve it. Thanks

**Comment by mindrunner** [comment] 2015-06-16 14:31
+1

same problem here. Any news on that?

**Comment by mindrunner** [comment] 2015-06-16 14:40
duplicate of #226

**Comment by h4ck3rviv3k** [comment] 2015-07-08 07:23
@rudsonliv

**Comment by h4ck3rviv3k** [comment] 2015-07-08 07:29
@neokree Please have a look into this issue I am still facing it

**Closed** 2015-12-22 18:31 UTC
