### ISSUE TITLE
When only one account is added,userSecondPhoto and userThirdPhoto shouldn't be clickable

### ISSUE THREAD

**Issue by tankilo** [neokree/MaterialNavigationDrawer#178] opened 2015-02-14 11:54 UTC
![aa](https://cloud.githubusercontent.com/assets/10413284/6199514/454f5e76-b483-11e4-9f8e-5e4dccc27e7e.jpg)

**Comment by neokree** [comment] 2015-02-14 12:50
userSecondPhoto and userThirdPhoto are always present, but user don't see his presence. When the user click on the view, the background listener is attached and called.

**Comment by tankilo** [comment] 2015-02-15 01:20
@neokree I didn't express clearly.If there is one acconut, I mean when you click userSecondPhoto and userThirdPhoto button , it should trigger the userButtonSwitcher instead of onAccountOpening.

**Comment by neokree** [comment] 2015-02-15 11:07
Oh, yes. It should be so. 
I will add a fix for this

**Comment by neokree** [comment] 2015-02-15 11:18
Sorry, I can't add some comments releated to the issue in the commit and github close automatically the issues

**Comment by neokree** [comment] 2015-02-17 02:23
Ok this fix is online with the 1.3.2 version

**Closed by neokree** 2015-02-17 02:23 UTC
Labels: available in the next release, request

**Comment by pawelantczak** [comment] 2015-02-18 19:54
On 1.3.2 the problem is still there.

**Comment by aimanbaharum** [comment] 2015-03-08 21:40
I noticed that this problem still exists. When you click user account 2 or 3, it will change the sections, which if I want only one account, the section will be empty when clicked. Perhaps, someone could remove the component or make it unclickable at least?

Great library btw! Thanks for making this.

**Comment by hth** [comment] 2015-06-26 05:51
I waiting on this solution too. If there is just one account, user info should be un-clickable and menu should not close.
